# This is the configuration file for Dependabot
version: 2
updates:
  
  # 1. Check for NPM (Node.js) dependency updates
  - package-ecosystem: "npm"
    # Look for package.json in the root directory
    directory: "/"
    schedule:
      # Check for updates every day
      interval: "daily"
    # This will create PRs with a branch prefix "dependabot/npm/..."
    pull-request-branch-name:
      separator: "/"

  # 2. Check for GitHub Actions (workflow) updates
  - package-ecosystem: "github-actions"
    # Look for .yml files in the .github/workflows directory
    directory: "/"
    schedule:
      # Check for updates every day
      interval: "daily"
    pull-request-branch-name:
      separator: "/"
