name: Code Review

on:
    pull_request:
        branches: [main]

jobs:
    code_review:
        runs-on: ubuntu-latest

        
        steps:
            # Retrieve repo
            - name: Checkout repository
              uses: actions/checkout@v4
            
              # Initialize CodeQl
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: javascript
            
            - name: Run code review
              uses: github/codeql-action/analyze@v3


            
            
            

            


    